### ISSUE TITLE
"jsig/type-check" instead of "type-check"

### ISSUE THREAD

**Issue by tinchoz49** [Raynos/eslint-plugin-jsig#1]
Hi Raynos, how are you?

I'm testing the plugin and it works great. I'm using it with the atom-eslint :+1: 

But using the eslint config that you provided in the readme did not work to me, i had to replace "type-check" by "jsig/type-check"

Does this make sense or i'm doing something wrong?

**Comment by Raynos** [comment]
This is correct. It's `jsig/type-check`, I made a mistake :)

**Comment by tinchoz49** [comment]
Thanks! jsig and now this plugin are really great ideas :)!

**Comment by Raynos** [comment]
@tinchoz49 

If you find any edgecases / bugs with `jsig` feel free to open an issue with a link to a reproduction case on ( http://raynos.github.io/jsig/ ).
